### PR TITLE
Test data

### PR DESCRIPTION
**Pull request by a-arefina**
Add a subset of an open seismic dataset as data for tests and demonstration

### CODE REVIEW

**Comment by a-arefina** [comment]
[Подготовить segy файл для тестов](https://trello.com/c/d8SiM57L/34-%D0%BF%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-segy-%D1%84%D0%B0%D0%B9%D0%BB-%D0%B4%D0%BB%D1%8F-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2)

**Comment by nikita-klsh** [comment]
Name `Test data` is ambiguous. 
The first thought is that this is the data for the validation of our models, not for `seismicpro/tests`.

**Comment by nikita-klsh** [comment]
Can this small segy for tests actually be located directly at `seismicpro/tests`? 
And does he deserves the individual `.ipynb` with description? You provide an exhaustive description in `seismicpro/src/tests/crop_test.py `. 

Alternatively, to clarify structure you can rename folder `data` to the name of the dataset, like `Teapot dome 3D openset`, and place there `.segy` and `.ipynb` next to each other.

**Comment by a-arefina** [comment]
> Can this small segy for tests actually be located directly at `seismicpro/tests`?
> And does he deserves the individual `.ipynb` with description? You provide an exhaustive description in `seismicpro/src/tests/crop_test.py `.

This is not only for tests. We can also use this dataset in our tutorials, so i'd prefer to leave it as is

**Comment by a-arefina** [comment]
this waits for #24 with pylint fixes

**Comment by a-arefina** [comment]
*.sgy are stored now in git-lfs

after this branch is merged into master everyone who wishes to work with it will have to install git-lfs extension as described at https://git-lfs.github.com/

**Pull request merged**
